[package]
name = "yt-client"
version = "0.1.0"
authors = ["gahag <gabriel.s.b@live.com>", "haneybarg <fernandaguimaraes28@gmail.com>", "Valeria Souza <souza.pereira.valeria@gmail.com>"]
edition = "2018"

[dependencies]
